name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2.12'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/tasks_management.sql
    - name: Database migrate
      run: php artisan migrate
    - name: Execute seeders
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: tasks_management
        DB_PORT: 33306
        DB_USER: root
        DB_PASSWORD:
      run: |
        php artisan migrate
        vendor/phpunit/phpunit/phpunit
