name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306:3306
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2.12'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/tasks_management.sql
    - name: Create databases
      run: |
        mkdir -p database
        touch database/tasks_management.sql
        mysql -e 'CREATE DATABASE tasks_management' -h127.0.0.1 -uroot -ppassword -P ${{ job.services.mysql.ports[3306] }}

    - name: Run test suite (MySQL)
      run: vendor/bin/phpunit --testdox --testsuite feature
      env:
        APP_KEY: base64:i3g6f+dV8FfsIkcxqd7gbiPn2oXk5r00sTmdD6V5utI=
        DB_CONNECTION: mysql
        DB_DATABASE: testbench
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_USERNAME: root
        DB_PASSWORD: password
    - name: TEST
      run : php artisan test
    
